# Generated by Django 5.2 on 2026-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order_gift_wrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, choices=[('general', 'General Inquiry'), ('order', 'Order Support'), ('product', 'Product Question'), ('wholesale', 'Wholesale / Partnership'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=30, null=True)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='ecommerce_c_email_3624f2_idx'), models.Index(fields=['created_at'], name='ecommerce_c_created_fae9da_idx')],
            },
        ),
    ]
